name: Flutter CI/CD

on:
  push:
    branches: master
  pull_request:
    types: [opened, synchronize, reopened, edited]
  pull_request_review:

jobs:
  build:
    name: Test & Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.1.1
      with:
        channel: 'stable'
    - name: Cache packages
      uses: actions/cache@v1
      with:
        path: $HOME/.pub-cache
        key: pub-${{ hashFiles('chronus_clock/pubspec.lock') }}
    - run: flutter pub get
    - name: Run tests
      run: echo "##[set-output name=result;]$(flutter test)"
      working-directory: chronus_clock
      id: test
    - uses: appleboy/telegram-action@master
      if: failure()
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          Tests failed on ${{ github.repository }} !!
          `${{ github.ref }}` triggered by ${{ github.actor }}
          - Event: ${{ github.event_name }}
          - SHA: `${{ github.sha }}`
          ```
          ${{ steps.test.outputs.result }}
          ```
    - name: Build
      run: echo "##[set-output name=result;]$(flutter build apk --debug --split-per-abi)"
      working-directory: chronus_clock
      id: build
    - uses: appleboy/telegram-action@master
      if: failure()
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          Build failed on ${{ github.repository }} !!
          `${{ github.ref }}` triggered by ${{ github.actor }}
          - Event: ${{ github.event_name }}
          - SHA: `${{ github.sha }}`
          ```
          ${{ steps.build.outputs.result }}
          ```
    - name: Upload build output
      uses: actions/upload-artifact@master
      with:
        name: build
        path: chronus_clock/build/app/outputs/apk/debug/

  notify:
    name: Notify result
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      - name: Download build output
        uses: actions/download-artifact@v1
        with:
          name: outputs
      - shell: bash
        run: zip -r build.zip outputs/
      - name: Notify on Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            Successfuly built ${{ github.repository }}
            `${{ github.ref }}` triggered by ${{ github.actor }}
          document: build.zip
